version: "3"

services:
  nginx:
    build:
      context: ./deploy/nginx
      dockerfile: Dockerfile
    container_name: "php-fpm-nginx-genesis"
    restart: unless-stopped
    networks:
      php-cms-iis:
        ipv4_address: 177.160.0.57
    volumes:
      - ./client/dist/:/var/www/html/
    ports: 
      - 8082:80
  
  php:
    build:
      context: .
      dockerfile: deploy/php/Dockerfile
    container_name: "php-fpm-cms-genesis"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - php-cms-iis
    volumes:
      - ./src/php/:/var/www/html/

networks:
  php-cms-iis:
    driver: bridge
    ipam:
      config:
        - subnet: 177.160.0.0/24
