version: "3"

services:
  nginx:
    build:
      context: ./deploy/nginx
      dockerfile: Dockerfile
    container_name: "php-fpm-nginx-genesis"
    restart: unless-stopped
    networks:
      php-cms-genesis:
        ipv4_address: 177.169.0.57
    volumes:
      - ./client/dist/:/var/www/html/
  
  php:
    build:
      context: .
      dockerfile: deploy/php/Dockerfile
    container_name: "php-fpm-cms-genesis"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - php-cms-genesis
    volumes:
      - ./src/php/:/var/www/html/

networks:
  php-cms-genesis:
    driver: bridge
    ipam:
      config:
        - subnet: 177.169.0.0/24
