/** Shapes returned by the Django catalog API (see ../genesis, apps/games). */

export type NameRef = {
  id: number;
  name: string;
};

export type Game = {
  id: number;
  /** Primary title first, then any alternative titles. */
  titles_list: string[];
  author: NameRef | null;
  description: string | null;
  screen_shots_list: string[];
  cover_image: string | null;
  /** Human readable playtime generated by the backend from the hour range. */
  duration: string;
  duration_hours_min: number | null;
  duration_hours_max: number | null;
  duration_type: NameRef;
  genres: NameRef[];
  competencies: NameRef[];
  platforms: NameRef[];
  modes: NameRef[];
};

export type Paginated<T> = {
  count: number;
  next: string | null;
  previous: string | null;
  results: T[];
};

/** The five reference lists the catalog filters are built from. */
export type Facets = {
  platforms: NameRef[];
  durations: NameRef[];
  modes: NameRef[];
  genres: NameRef[];
  competencies: NameRef[];
};

export type FacetKey =
  | "platforms"
  | "durations"
  | "modes"
  | "genres"
  | "competencies";

/**
 * Query parameter each facet maps to. `durations` is the user-facing name of
 * the backend's `duration_type` filter.
 */
export const FACET_PARAM = {
  platforms: "platforms",
  durations: "duration_type",
  modes: "modes",
  genres: "genres",
  competencies: "competencies",
} as const;

export type SelectedFacets = Record<FacetKey, number[]>;

export const EMPTY_SELECTION: SelectedFacets = {
  platforms: [],
  durations: [],
  modes: [],
  genres: [],
  competencies: [],
};

export const FACET_LABELS: Record<FacetKey, string> = {
  platforms: "Платформа",
  durations: "Продолжительность",
  modes: "Режим игры",
  genres: "Жанр",
  competencies: "Компетенции",
};
